### ISSUE TITLE
Add xformers on requirements.txt

### ISSUE THREAD

**Issue by heitorrapela** [omer11a/bounded-attention#2]
![image](https://github.com/omer11a/bounded-attention/assets/14017613/45c4d257-0a20-4046-8815-05e47131badb)

If someone wants to use the `run_xl.py`, we need to install xformers, which is not on the `requirements.txt`, also the code does not work with python 3.8, so I had to upgrade to python 3.11.

If someone finds the same problem: `pip install xformers`

**Comment by omer11a** [comment]
Thank you!
I've added former's to requirements.txt.
