### ISSUE TITLE
[NLTK Error]

### ISSUE THREAD

**Issue by heitorrapela** [omer11a/bounded-attention#3]
If someone get the following error to when running the `run_xl.py`

![image](https://github.com/omer11a/bounded-attention/assets/14017613/17a281b3-8ccb-4acf-8155-d31dc1e931b6)

Solution: https://stackoverflow.com/questions/35861482/nltk-lookup-error

You can install what is in the image, or you can install as I did:
`python3 -c "import nltk; nltk.download('all')"`

**Comment by omer11a** [comment]
Thank you!
I've updated README.md to include this
