### ISSUE TITLE
get baseline results 

### ISSUE THREAD

**Issue by dain5832** [omer11a/bounded-attention#5]
Hi, thanks for the wonderful work!

I would like to ask how can I get the baseline results using the code in the repo.

I tried to set init_step_size and final_step_size to 0, so that the step size of latent updates process becomes 0.
However, the result seems to include the box condition.
![286_0_0_boxes](https://github.com/omer11a/bounded-attention/assets/62231006/ec5ae18f-84f3-4856-9647-d0a2f83efbf3)

**Comment by omer11a** [comment]
To recreate the baseline results, please use the hyper-parameters in our example in run_xl.py, i.e. init_step_size=25 and final_step_size=10. Setting them to zero cancels the optimization phase, which is necessary for proper alignment with the prompt and layout.
The script creates two images, one that includes the boxes and one without them.
