### ISSUE TITLE
Get the M of self-attn

### ISSUE THREAD

**Issue by KoTion** [omer11a/bounded-attention#9]
The M obtained by the function _hide_other_subjects_from_subjects is all 0, which means that the result of self-attn is still the result of Q*K, not the result of bounded attention.

The results of subject_masks and background_masks obtained in function _hide_other_subjects_from_subjects are as follows：
![image](https://github.com/omer11a/bounded-attention/assets/49680625/f211f572-3075-4a64-9851-a0782fb65e21)
That is right

However, after the following code operation, the returned sim_masks are all 0.

**Comment by omer11a** [comment]
Great find. Thanks!
I fixed it now
